### ISSUE TITLE
Question about Oracle

### ISSUE THREAD

**Issue by Draichi** [GiantPay/GiantExchange#2]
Hi dude, i was loking to this code and i have a question, what are thsoe funcitons in `mocks/index.js`? Its something related to the blockchain connection? Like a placeholder

Thanks, 

project is looking good :+1:

**Comment by tursumbekov** [comment]
Hi, thanks for the feedback. This is a mock object that is needed for testing. In the release version, this will be the backend application for providing data about the Oracle.
